name: Admin CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install admin deps
        working-directory: admin
        run: |
          cd admin
          npm ci
      - name: Build admin
        working-directory: admin
        run: |
          npm run build || echo "build step (react-scripts)"
